---
- hosts: localhost
  become: true
  roles:
    - efs
    - mysql
    - apache
- name: Start the web service
  service:
    name: mysql
    state: started
- name: Start the web service
  service:
    name: apache
    state: started
